//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMSEntities : DbContext
    {
        public AMSEntities()
            : base("name=AMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SYS_TELLER_INFO> SYS_TELLER_INFO { get; set; }
        public DbSet<SYS_USER> SYS_USER { get; set; }
        public DbSet<TRANS_AUDIT> TRANS_AUDIT { get; set; }
        public DbSet<TRANS_MAIN> TRANS_MAIN { get; set; }
        public DbSet<TRANS_TYPE> TRANS_TYPE { get; set; }
    }
}
