//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TELLER_INFO
    {
        public string TELLER_ID { get; set; }
        public string UNIT_ID { get; set; }
        public string DEPT_ID { get; set; }
        public Nullable<double> ROW_ID { get; set; }
        public string PASSWORD { get; set; }
        public string TELLER_ROLE { get; set; }
        public string CUST_NAME { get; set; }
        public string SEX { get; set; }
        public string SIGN_STATE { get; set; }
        public string SIGN_ON_DATETIME { get; set; }
        public string SIGN_OFF_DATETIME { get; set; }
        public string CAN_COMMIT { get; set; }
        public string BIRTHDAY { get; set; }
        public string START_JOB_DATE { get; set; }
        public string ID_CARD { get; set; }
        public string EMPLOYEE_CARD_ID { get; set; }
        public string NATIVE_PLACE { get; set; }
        public string HOME_ADDR { get; set; }
        public string EDU_LEV { get; set; }
        public string TOP_DEGREE { get; set; }
        public string IS_MARRIED { get; set; }
        public string POLITY { get; set; }
        public string DUTY { get; set; }
        public string TITLE_TECHNICAL_POST { get; set; }
        public string STATION { get; set; }
        public string STATION_ID { get; set; }
        public string UPPER_UNIT_NAME { get; set; }
        public string TEL_WROK { get; set; }
        public string MOBIL { get; set; }
        public string TEL_HOME { get; set; }
        public string EMAIL { get; set; }
        public string REMARK { get; set; }
        public string UNIT { get; set; }
        public string USER_ID { get; set; }
        public string RECORD_STATE { get; set; }
    }
}
